[tool.poetry]
name = "drobkov-bogdan-mlops-taxi-forecast"
version = "0.1.0"
description = "MLOps taxi order forecasting"
authors = ["Bogdan Drobkov <drobkov@example.com>"]
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
pandas = "*"
numpy = "*"
scikit-learn = "*"
matplotlib = "*"
seaborn = "*"
catboost = "*"
mlflow = "*"
joblib = "*"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pre-commit = "*"
ruff = "*"
nbqa = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.ruff]
line-length = 100
target-version = "py311"
extend-exclude = ["notebooks/", "reports/", "models/", "data/"]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "N",
    "UP",
    "B",
    "W",
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/*" = ["S101"]
"*.ipynb" = ["B018", "F821"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --tb=short"
